version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn --config gunicorn.conf.py myproject.wsgi:application
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    networks:
      Docker-network:
        ipv4_address: 10.0.0.10

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django-db
    networks:
      Docker-network:
        ipv4_address: 10.0.0.21

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      Docker-network:
        ipv4_address: 10.0.0.11

volumes:
  postgres_data:

networks:
  Docker-network:
    external: true
